---
- hosts: dev
  become: true
  tasks:
    - name: Install python pip
      apt:
        name: python3-pip
        state: present

    - name: Install docker
      apt:
        name: docker.io
        state: present

    - name: Start docker service
      service:
        name: docker
        state: started
        enabled: yes

    # - name: Install python3-venv package
    #   apt:
    #     name: python3.12-venv
    #     state: present
    #     update_cache: yes  # Update package cache before installing

    # - name: Create a virtual environment
    #   command: python3 -m venv /path/to/venv
    #   args:
    #     creates: /path/to/venv  # Ensure this command only runs if the venv doesn't exist

    - name: Activate the virtual environment
      shell: source /path/to/venv/bin/activate

    - name: Install docker-py in the virtual environment
      pip:
        name: docker-py
        state: present
