---
- hosts: dev
  become: true
  tasks:
    - name: Install python pip
      apt:
        name: python3-pip
        state: present

    - name: Install docker
      apt:
        name: docker.io
        state: present

    - name: Start docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install docker-py python module using system package manager
      apt:
        name: python3-docker
        state: present

    - name: Create a virtual environment and install docker-py
      command: |
        python3 -m venv /path/to/venv &&
        source /path/to/venv/bin/activate &&
        pip install docker-py

    - name: Start the container
      docker_container:
        name: ikanContainer
        image: "adlaniq/ikan:{{ DOCKER_TAG }}"
        state: started
        published_ports:
          - "0.0.0.0:8080:8080"
